"""remove_cart_quantity

Revision ID: 928ea4b306c8
Revises: cbb97f2c33bf
Create Date: 2023-03-19 08:47:34.542083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "928ea4b306c8"
down_revision = "cbb97f2c33bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart", sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
