"""rename_cart_item_quantity

Revision ID: ed2194249a78
Revises: 7ce5f25e245f
Create Date: 2023-03-19 10:45:07.889920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed2194249a78"
down_revision = "7ce5f25e245f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cart_item", sa.Column("quantity", sa.Integer(), nullable=False))
    op.drop_column("cart_item", "product_quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_item",
        sa.Column(
            "product_quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("cart_item", "quantity")
    # ### end Alembic commands ###
