"""add_cart_product_quantity_field

Revision ID: c04a57b7015f
Revises: 928ea4b306c8
Create Date: 2023-03-19 09:13:21.359623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c04a57b7015f"
down_revision = "928ea4b306c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cart_product", sa.Column("product_quantity", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cart_product", "product_quantity")
    # ### end Alembic commands ###
