"""change_fk_customer_id_to_user_id

Revision ID: e7760819ae93
Revises: c04a57b7015f
Create Date: 2023-03-19 09:45:24.614396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7760819ae93"
down_revision = "c04a57b7015f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cart", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("cart_customer_id_fkey", "cart", type_="foreignkey")
    op.create_foreign_key(
        op.f("cart_user_id_fkey"),
        "cart",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("cart", "customer_id")
    op.add_column("order", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("order_customer_id_fkey", "order", type_="foreignkey")
    op.create_foreign_key(
        op.f("order_user_id_fkey"),
        "order",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("order", "customer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("order_user_id_fkey"), "order", type_="foreignkey")
    op.create_foreign_key(
        "order_customer_id_fkey",
        "order",
        "customer",
        ["customer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("order", "user_id")
    op.add_column(
        "cart",
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("cart_user_id_fkey"), "cart", type_="foreignkey")
    op.create_foreign_key(
        "cart_customer_id_fkey",
        "cart",
        "customer",
        ["customer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("cart", "user_id")
    # ### end Alembic commands ###
